version: "3.9"

services:
  syma_web:
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - syma_db
    environment:
      DJANGO_DB_HOST: syma_db
      DJANGO_DB_PORT: 3306
      DJANGO_DB_NAME: syma_db
      DJANGO_DB_USER: root
      DJANGO_DB_PASSWORD: root

  syma_db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: syma_db

volumes: 
  mysql_data: