version: '3.8'

services:
  # 1. Aplicaci√≥n Web (Django + Gunicorn)
  syma_web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn syma.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static_volume:/app/staticFiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file: .prod.env
    depends_on:
      - syma_db
      - syma_redis
    restart: always

  # 2. Worker de Celery (Para tareas de fondo y escalabilidad)
  syma_worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A syma worker -l info
    env_file: .prod.env
    depends_on:
      - syma_db
      - syma_redis
    volumes:
      - media_volume:/app/media
    restart: always

  # 3. Base de Datos
  syma_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: .prod.env
    restart: always

  # 4. Redis (Broker para Celery)
  syma_redis:
    image: redis:alpine
    restart: always

  # 5. Servidor Web (Nginx)
  syma_nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticFiles
      - media_volume:/app/media
    depends_on:
      - syma_web
    restart: always

volumes:
  mysql_data:
  static_volume:
  media_volume: